// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"context"
	"sync"

	"github.com/dgdraganov/user-api/internal/core"
	"github.com/dgdraganov/user-api/internal/repository"
)

type Repository struct {
	CreateUserStub        func(context.Context, repository.User) error
	createUserMutex       sync.RWMutex
	createUserArgsForCall []struct {
		arg1 context.Context
		arg2 repository.User
	}
	createUserReturns struct {
		result1 error
	}
	createUserReturnsOnCall map[int]struct {
		result1 error
	}
	GetUserByEmailStub        func(context.Context, string, *repository.User) error
	getUserByEmailMutex       sync.RWMutex
	getUserByEmailArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 *repository.User
	}
	getUserByEmailReturns struct {
		result1 error
	}
	getUserByEmailReturnsOnCall map[int]struct {
		result1 error
	}
	GetUserByIDStub        func(context.Context, string, *repository.User) error
	getUserByIDMutex       sync.RWMutex
	getUserByIDArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 *repository.User
	}
	getUserByIDReturns struct {
		result1 error
	}
	getUserByIDReturnsOnCall map[int]struct {
		result1 error
	}
	ListUsersByPageStub        func(context.Context, int, int, *[]repository.User) error
	listUsersByPageMutex       sync.RWMutex
	listUsersByPageArgsForCall []struct {
		arg1 context.Context
		arg2 int
		arg3 int
		arg4 *[]repository.User
	}
	listUsersByPageReturns struct {
		result1 error
	}
	listUsersByPageReturnsOnCall map[int]struct {
		result1 error
	}
	SaveFileMetadataStub        func(context.Context, repository.FileMetadata) error
	saveFileMetadataMutex       sync.RWMutex
	saveFileMetadataArgsForCall []struct {
		arg1 context.Context
		arg2 repository.FileMetadata
	}
	saveFileMetadataReturns struct {
		result1 error
	}
	saveFileMetadataReturnsOnCall map[int]struct {
		result1 error
	}
	UpdateUserStub        func(context.Context, repository.User) error
	updateUserMutex       sync.RWMutex
	updateUserArgsForCall []struct {
		arg1 context.Context
		arg2 repository.User
	}
	updateUserReturns struct {
		result1 error
	}
	updateUserReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Repository) CreateUser(arg1 context.Context, arg2 repository.User) error {
	fake.createUserMutex.Lock()
	ret, specificReturn := fake.createUserReturnsOnCall[len(fake.createUserArgsForCall)]
	fake.createUserArgsForCall = append(fake.createUserArgsForCall, struct {
		arg1 context.Context
		arg2 repository.User
	}{arg1, arg2})
	stub := fake.CreateUserStub
	fakeReturns := fake.createUserReturns
	fake.recordInvocation("CreateUser", []interface{}{arg1, arg2})
	fake.createUserMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Repository) CreateUserCallCount() int {
	fake.createUserMutex.RLock()
	defer fake.createUserMutex.RUnlock()
	return len(fake.createUserArgsForCall)
}

func (fake *Repository) CreateUserCalls(stub func(context.Context, repository.User) error) {
	fake.createUserMutex.Lock()
	defer fake.createUserMutex.Unlock()
	fake.CreateUserStub = stub
}

func (fake *Repository) CreateUserArgsForCall(i int) (context.Context, repository.User) {
	fake.createUserMutex.RLock()
	defer fake.createUserMutex.RUnlock()
	argsForCall := fake.createUserArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Repository) CreateUserReturns(result1 error) {
	fake.createUserMutex.Lock()
	defer fake.createUserMutex.Unlock()
	fake.CreateUserStub = nil
	fake.createUserReturns = struct {
		result1 error
	}{result1}
}

func (fake *Repository) CreateUserReturnsOnCall(i int, result1 error) {
	fake.createUserMutex.Lock()
	defer fake.createUserMutex.Unlock()
	fake.CreateUserStub = nil
	if fake.createUserReturnsOnCall == nil {
		fake.createUserReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createUserReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Repository) GetUserByEmail(arg1 context.Context, arg2 string, arg3 *repository.User) error {
	fake.getUserByEmailMutex.Lock()
	ret, specificReturn := fake.getUserByEmailReturnsOnCall[len(fake.getUserByEmailArgsForCall)]
	fake.getUserByEmailArgsForCall = append(fake.getUserByEmailArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 *repository.User
	}{arg1, arg2, arg3})
	stub := fake.GetUserByEmailStub
	fakeReturns := fake.getUserByEmailReturns
	fake.recordInvocation("GetUserByEmail", []interface{}{arg1, arg2, arg3})
	fake.getUserByEmailMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Repository) GetUserByEmailCallCount() int {
	fake.getUserByEmailMutex.RLock()
	defer fake.getUserByEmailMutex.RUnlock()
	return len(fake.getUserByEmailArgsForCall)
}

func (fake *Repository) GetUserByEmailCalls(stub func(context.Context, string, *repository.User) error) {
	fake.getUserByEmailMutex.Lock()
	defer fake.getUserByEmailMutex.Unlock()
	fake.GetUserByEmailStub = stub
}

func (fake *Repository) GetUserByEmailArgsForCall(i int) (context.Context, string, *repository.User) {
	fake.getUserByEmailMutex.RLock()
	defer fake.getUserByEmailMutex.RUnlock()
	argsForCall := fake.getUserByEmailArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *Repository) GetUserByEmailReturns(result1 error) {
	fake.getUserByEmailMutex.Lock()
	defer fake.getUserByEmailMutex.Unlock()
	fake.GetUserByEmailStub = nil
	fake.getUserByEmailReturns = struct {
		result1 error
	}{result1}
}

func (fake *Repository) GetUserByEmailReturnsOnCall(i int, result1 error) {
	fake.getUserByEmailMutex.Lock()
	defer fake.getUserByEmailMutex.Unlock()
	fake.GetUserByEmailStub = nil
	if fake.getUserByEmailReturnsOnCall == nil {
		fake.getUserByEmailReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.getUserByEmailReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Repository) GetUserByID(arg1 context.Context, arg2 string, arg3 *repository.User) error {
	fake.getUserByIDMutex.Lock()
	ret, specificReturn := fake.getUserByIDReturnsOnCall[len(fake.getUserByIDArgsForCall)]
	fake.getUserByIDArgsForCall = append(fake.getUserByIDArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 *repository.User
	}{arg1, arg2, arg3})
	stub := fake.GetUserByIDStub
	fakeReturns := fake.getUserByIDReturns
	fake.recordInvocation("GetUserByID", []interface{}{arg1, arg2, arg3})
	fake.getUserByIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Repository) GetUserByIDCallCount() int {
	fake.getUserByIDMutex.RLock()
	defer fake.getUserByIDMutex.RUnlock()
	return len(fake.getUserByIDArgsForCall)
}

func (fake *Repository) GetUserByIDCalls(stub func(context.Context, string, *repository.User) error) {
	fake.getUserByIDMutex.Lock()
	defer fake.getUserByIDMutex.Unlock()
	fake.GetUserByIDStub = stub
}

func (fake *Repository) GetUserByIDArgsForCall(i int) (context.Context, string, *repository.User) {
	fake.getUserByIDMutex.RLock()
	defer fake.getUserByIDMutex.RUnlock()
	argsForCall := fake.getUserByIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *Repository) GetUserByIDReturns(result1 error) {
	fake.getUserByIDMutex.Lock()
	defer fake.getUserByIDMutex.Unlock()
	fake.GetUserByIDStub = nil
	fake.getUserByIDReturns = struct {
		result1 error
	}{result1}
}

func (fake *Repository) GetUserByIDReturnsOnCall(i int, result1 error) {
	fake.getUserByIDMutex.Lock()
	defer fake.getUserByIDMutex.Unlock()
	fake.GetUserByIDStub = nil
	if fake.getUserByIDReturnsOnCall == nil {
		fake.getUserByIDReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.getUserByIDReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Repository) ListUsersByPage(arg1 context.Context, arg2 int, arg3 int, arg4 *[]repository.User) error {
	fake.listUsersByPageMutex.Lock()
	ret, specificReturn := fake.listUsersByPageReturnsOnCall[len(fake.listUsersByPageArgsForCall)]
	fake.listUsersByPageArgsForCall = append(fake.listUsersByPageArgsForCall, struct {
		arg1 context.Context
		arg2 int
		arg3 int
		arg4 *[]repository.User
	}{arg1, arg2, arg3, arg4})
	stub := fake.ListUsersByPageStub
	fakeReturns := fake.listUsersByPageReturns
	fake.recordInvocation("ListUsersByPage", []interface{}{arg1, arg2, arg3, arg4})
	fake.listUsersByPageMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Repository) ListUsersByPageCallCount() int {
	fake.listUsersByPageMutex.RLock()
	defer fake.listUsersByPageMutex.RUnlock()
	return len(fake.listUsersByPageArgsForCall)
}

func (fake *Repository) ListUsersByPageCalls(stub func(context.Context, int, int, *[]repository.User) error) {
	fake.listUsersByPageMutex.Lock()
	defer fake.listUsersByPageMutex.Unlock()
	fake.ListUsersByPageStub = stub
}

func (fake *Repository) ListUsersByPageArgsForCall(i int) (context.Context, int, int, *[]repository.User) {
	fake.listUsersByPageMutex.RLock()
	defer fake.listUsersByPageMutex.RUnlock()
	argsForCall := fake.listUsersByPageArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *Repository) ListUsersByPageReturns(result1 error) {
	fake.listUsersByPageMutex.Lock()
	defer fake.listUsersByPageMutex.Unlock()
	fake.ListUsersByPageStub = nil
	fake.listUsersByPageReturns = struct {
		result1 error
	}{result1}
}

func (fake *Repository) ListUsersByPageReturnsOnCall(i int, result1 error) {
	fake.listUsersByPageMutex.Lock()
	defer fake.listUsersByPageMutex.Unlock()
	fake.ListUsersByPageStub = nil
	if fake.listUsersByPageReturnsOnCall == nil {
		fake.listUsersByPageReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.listUsersByPageReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Repository) SaveFileMetadata(arg1 context.Context, arg2 repository.FileMetadata) error {
	fake.saveFileMetadataMutex.Lock()
	ret, specificReturn := fake.saveFileMetadataReturnsOnCall[len(fake.saveFileMetadataArgsForCall)]
	fake.saveFileMetadataArgsForCall = append(fake.saveFileMetadataArgsForCall, struct {
		arg1 context.Context
		arg2 repository.FileMetadata
	}{arg1, arg2})
	stub := fake.SaveFileMetadataStub
	fakeReturns := fake.saveFileMetadataReturns
	fake.recordInvocation("SaveFileMetadata", []interface{}{arg1, arg2})
	fake.saveFileMetadataMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Repository) SaveFileMetadataCallCount() int {
	fake.saveFileMetadataMutex.RLock()
	defer fake.saveFileMetadataMutex.RUnlock()
	return len(fake.saveFileMetadataArgsForCall)
}

func (fake *Repository) SaveFileMetadataCalls(stub func(context.Context, repository.FileMetadata) error) {
	fake.saveFileMetadataMutex.Lock()
	defer fake.saveFileMetadataMutex.Unlock()
	fake.SaveFileMetadataStub = stub
}

func (fake *Repository) SaveFileMetadataArgsForCall(i int) (context.Context, repository.FileMetadata) {
	fake.saveFileMetadataMutex.RLock()
	defer fake.saveFileMetadataMutex.RUnlock()
	argsForCall := fake.saveFileMetadataArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Repository) SaveFileMetadataReturns(result1 error) {
	fake.saveFileMetadataMutex.Lock()
	defer fake.saveFileMetadataMutex.Unlock()
	fake.SaveFileMetadataStub = nil
	fake.saveFileMetadataReturns = struct {
		result1 error
	}{result1}
}

func (fake *Repository) SaveFileMetadataReturnsOnCall(i int, result1 error) {
	fake.saveFileMetadataMutex.Lock()
	defer fake.saveFileMetadataMutex.Unlock()
	fake.SaveFileMetadataStub = nil
	if fake.saveFileMetadataReturnsOnCall == nil {
		fake.saveFileMetadataReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.saveFileMetadataReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Repository) UpdateUser(arg1 context.Context, arg2 repository.User) error {
	fake.updateUserMutex.Lock()
	ret, specificReturn := fake.updateUserReturnsOnCall[len(fake.updateUserArgsForCall)]
	fake.updateUserArgsForCall = append(fake.updateUserArgsForCall, struct {
		arg1 context.Context
		arg2 repository.User
	}{arg1, arg2})
	stub := fake.UpdateUserStub
	fakeReturns := fake.updateUserReturns
	fake.recordInvocation("UpdateUser", []interface{}{arg1, arg2})
	fake.updateUserMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Repository) UpdateUserCallCount() int {
	fake.updateUserMutex.RLock()
	defer fake.updateUserMutex.RUnlock()
	return len(fake.updateUserArgsForCall)
}

func (fake *Repository) UpdateUserCalls(stub func(context.Context, repository.User) error) {
	fake.updateUserMutex.Lock()
	defer fake.updateUserMutex.Unlock()
	fake.UpdateUserStub = stub
}

func (fake *Repository) UpdateUserArgsForCall(i int) (context.Context, repository.User) {
	fake.updateUserMutex.RLock()
	defer fake.updateUserMutex.RUnlock()
	argsForCall := fake.updateUserArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Repository) UpdateUserReturns(result1 error) {
	fake.updateUserMutex.Lock()
	defer fake.updateUserMutex.Unlock()
	fake.UpdateUserStub = nil
	fake.updateUserReturns = struct {
		result1 error
	}{result1}
}

func (fake *Repository) UpdateUserReturnsOnCall(i int, result1 error) {
	fake.updateUserMutex.Lock()
	defer fake.updateUserMutex.Unlock()
	fake.UpdateUserStub = nil
	if fake.updateUserReturnsOnCall == nil {
		fake.updateUserReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateUserReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Repository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Repository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ core.Repository = new(Repository)
