// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"context"
	"io"
	"sync"

	"github.com/dgdraganov/user-api/internal/http/handler"
	"github.com/golang-jwt/jwt"
)

type FileService struct {
	SaveFileMetadataStub        func(context.Context, string, string, string) error
	saveFileMetadataMutex       sync.RWMutex
	saveFileMetadataArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}
	saveFileMetadataReturns struct {
		result1 error
	}
	saveFileMetadataReturnsOnCall map[int]struct {
		result1 error
	}
	UploadUserFileStub        func(context.Context, string, io.Reader, int64) error
	uploadUserFileMutex       sync.RWMutex
	uploadUserFileArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 io.Reader
		arg4 int64
	}
	uploadUserFileReturns struct {
		result1 error
	}
	uploadUserFileReturnsOnCall map[int]struct {
		result1 error
	}
	ValidateTokenStub        func(context.Context, string) (jwt.MapClaims, error)
	validateTokenMutex       sync.RWMutex
	validateTokenArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	validateTokenReturns struct {
		result1 jwt.MapClaims
		result2 error
	}
	validateTokenReturnsOnCall map[int]struct {
		result1 jwt.MapClaims
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FileService) SaveFileMetadata(arg1 context.Context, arg2 string, arg3 string, arg4 string) error {
	fake.saveFileMetadataMutex.Lock()
	ret, specificReturn := fake.saveFileMetadataReturnsOnCall[len(fake.saveFileMetadataArgsForCall)]
	fake.saveFileMetadataArgsForCall = append(fake.saveFileMetadataArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.SaveFileMetadataStub
	fakeReturns := fake.saveFileMetadataReturns
	fake.recordInvocation("SaveFileMetadata", []interface{}{arg1, arg2, arg3, arg4})
	fake.saveFileMetadataMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FileService) SaveFileMetadataCallCount() int {
	fake.saveFileMetadataMutex.RLock()
	defer fake.saveFileMetadataMutex.RUnlock()
	return len(fake.saveFileMetadataArgsForCall)
}

func (fake *FileService) SaveFileMetadataCalls(stub func(context.Context, string, string, string) error) {
	fake.saveFileMetadataMutex.Lock()
	defer fake.saveFileMetadataMutex.Unlock()
	fake.SaveFileMetadataStub = stub
}

func (fake *FileService) SaveFileMetadataArgsForCall(i int) (context.Context, string, string, string) {
	fake.saveFileMetadataMutex.RLock()
	defer fake.saveFileMetadataMutex.RUnlock()
	argsForCall := fake.saveFileMetadataArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FileService) SaveFileMetadataReturns(result1 error) {
	fake.saveFileMetadataMutex.Lock()
	defer fake.saveFileMetadataMutex.Unlock()
	fake.SaveFileMetadataStub = nil
	fake.saveFileMetadataReturns = struct {
		result1 error
	}{result1}
}

func (fake *FileService) SaveFileMetadataReturnsOnCall(i int, result1 error) {
	fake.saveFileMetadataMutex.Lock()
	defer fake.saveFileMetadataMutex.Unlock()
	fake.SaveFileMetadataStub = nil
	if fake.saveFileMetadataReturnsOnCall == nil {
		fake.saveFileMetadataReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.saveFileMetadataReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FileService) UploadUserFile(arg1 context.Context, arg2 string, arg3 io.Reader, arg4 int64) error {
	fake.uploadUserFileMutex.Lock()
	ret, specificReturn := fake.uploadUserFileReturnsOnCall[len(fake.uploadUserFileArgsForCall)]
	fake.uploadUserFileArgsForCall = append(fake.uploadUserFileArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 io.Reader
		arg4 int64
	}{arg1, arg2, arg3, arg4})
	stub := fake.UploadUserFileStub
	fakeReturns := fake.uploadUserFileReturns
	fake.recordInvocation("UploadUserFile", []interface{}{arg1, arg2, arg3, arg4})
	fake.uploadUserFileMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FileService) UploadUserFileCallCount() int {
	fake.uploadUserFileMutex.RLock()
	defer fake.uploadUserFileMutex.RUnlock()
	return len(fake.uploadUserFileArgsForCall)
}

func (fake *FileService) UploadUserFileCalls(stub func(context.Context, string, io.Reader, int64) error) {
	fake.uploadUserFileMutex.Lock()
	defer fake.uploadUserFileMutex.Unlock()
	fake.UploadUserFileStub = stub
}

func (fake *FileService) UploadUserFileArgsForCall(i int) (context.Context, string, io.Reader, int64) {
	fake.uploadUserFileMutex.RLock()
	defer fake.uploadUserFileMutex.RUnlock()
	argsForCall := fake.uploadUserFileArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FileService) UploadUserFileReturns(result1 error) {
	fake.uploadUserFileMutex.Lock()
	defer fake.uploadUserFileMutex.Unlock()
	fake.UploadUserFileStub = nil
	fake.uploadUserFileReturns = struct {
		result1 error
	}{result1}
}

func (fake *FileService) UploadUserFileReturnsOnCall(i int, result1 error) {
	fake.uploadUserFileMutex.Lock()
	defer fake.uploadUserFileMutex.Unlock()
	fake.UploadUserFileStub = nil
	if fake.uploadUserFileReturnsOnCall == nil {
		fake.uploadUserFileReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.uploadUserFileReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FileService) ValidateToken(arg1 context.Context, arg2 string) (jwt.MapClaims, error) {
	fake.validateTokenMutex.Lock()
	ret, specificReturn := fake.validateTokenReturnsOnCall[len(fake.validateTokenArgsForCall)]
	fake.validateTokenArgsForCall = append(fake.validateTokenArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.ValidateTokenStub
	fakeReturns := fake.validateTokenReturns
	fake.recordInvocation("ValidateToken", []interface{}{arg1, arg2})
	fake.validateTokenMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FileService) ValidateTokenCallCount() int {
	fake.validateTokenMutex.RLock()
	defer fake.validateTokenMutex.RUnlock()
	return len(fake.validateTokenArgsForCall)
}

func (fake *FileService) ValidateTokenCalls(stub func(context.Context, string) (jwt.MapClaims, error)) {
	fake.validateTokenMutex.Lock()
	defer fake.validateTokenMutex.Unlock()
	fake.ValidateTokenStub = stub
}

func (fake *FileService) ValidateTokenArgsForCall(i int) (context.Context, string) {
	fake.validateTokenMutex.RLock()
	defer fake.validateTokenMutex.RUnlock()
	argsForCall := fake.validateTokenArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FileService) ValidateTokenReturns(result1 jwt.MapClaims, result2 error) {
	fake.validateTokenMutex.Lock()
	defer fake.validateTokenMutex.Unlock()
	fake.ValidateTokenStub = nil
	fake.validateTokenReturns = struct {
		result1 jwt.MapClaims
		result2 error
	}{result1, result2}
}

func (fake *FileService) ValidateTokenReturnsOnCall(i int, result1 jwt.MapClaims, result2 error) {
	fake.validateTokenMutex.Lock()
	defer fake.validateTokenMutex.Unlock()
	fake.ValidateTokenStub = nil
	if fake.validateTokenReturnsOnCall == nil {
		fake.validateTokenReturnsOnCall = make(map[int]struct {
			result1 jwt.MapClaims
			result2 error
		})
	}
	fake.validateTokenReturnsOnCall[i] = struct {
		result1 jwt.MapClaims
		result2 error
	}{result1, result2}
}

func (fake *FileService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FileService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ handler.FileService = new(FileService)
