// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"net/http"
	"sync"

	"github.com/dgdraganov/user-api/internal/http/handler"
	"github.com/dgdraganov/user-api/internal/http/payload"
)

type RequestValidator struct {
	DecodeAndValidateJSONPayloadStub        func(*http.Request, any) error
	decodeAndValidateJSONPayloadMutex       sync.RWMutex
	decodeAndValidateJSONPayloadArgsForCall []struct {
		arg1 *http.Request
		arg2 any
	}
	decodeAndValidateJSONPayloadReturns struct {
		result1 error
	}
	decodeAndValidateJSONPayloadReturnsOnCall map[int]struct {
		result1 error
	}
	DecodeAndValidateQueryParamsStub        func(*http.Request, payload.URLDecoder) error
	decodeAndValidateQueryParamsMutex       sync.RWMutex
	decodeAndValidateQueryParamsArgsForCall []struct {
		arg1 *http.Request
		arg2 payload.URLDecoder
	}
	decodeAndValidateQueryParamsReturns struct {
		result1 error
	}
	decodeAndValidateQueryParamsReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *RequestValidator) DecodeAndValidateJSONPayload(arg1 *http.Request, arg2 any) error {
	fake.decodeAndValidateJSONPayloadMutex.Lock()
	ret, specificReturn := fake.decodeAndValidateJSONPayloadReturnsOnCall[len(fake.decodeAndValidateJSONPayloadArgsForCall)]
	fake.decodeAndValidateJSONPayloadArgsForCall = append(fake.decodeAndValidateJSONPayloadArgsForCall, struct {
		arg1 *http.Request
		arg2 any
	}{arg1, arg2})
	stub := fake.DecodeAndValidateJSONPayloadStub
	fakeReturns := fake.decodeAndValidateJSONPayloadReturns
	fake.recordInvocation("DecodeAndValidateJSONPayload", []interface{}{arg1, arg2})
	fake.decodeAndValidateJSONPayloadMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *RequestValidator) DecodeAndValidateJSONPayloadCallCount() int {
	fake.decodeAndValidateJSONPayloadMutex.RLock()
	defer fake.decodeAndValidateJSONPayloadMutex.RUnlock()
	return len(fake.decodeAndValidateJSONPayloadArgsForCall)
}

func (fake *RequestValidator) DecodeAndValidateJSONPayloadCalls(stub func(*http.Request, any) error) {
	fake.decodeAndValidateJSONPayloadMutex.Lock()
	defer fake.decodeAndValidateJSONPayloadMutex.Unlock()
	fake.DecodeAndValidateJSONPayloadStub = stub
}

func (fake *RequestValidator) DecodeAndValidateJSONPayloadArgsForCall(i int) (*http.Request, any) {
	fake.decodeAndValidateJSONPayloadMutex.RLock()
	defer fake.decodeAndValidateJSONPayloadMutex.RUnlock()
	argsForCall := fake.decodeAndValidateJSONPayloadArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *RequestValidator) DecodeAndValidateJSONPayloadReturns(result1 error) {
	fake.decodeAndValidateJSONPayloadMutex.Lock()
	defer fake.decodeAndValidateJSONPayloadMutex.Unlock()
	fake.DecodeAndValidateJSONPayloadStub = nil
	fake.decodeAndValidateJSONPayloadReturns = struct {
		result1 error
	}{result1}
}

func (fake *RequestValidator) DecodeAndValidateJSONPayloadReturnsOnCall(i int, result1 error) {
	fake.decodeAndValidateJSONPayloadMutex.Lock()
	defer fake.decodeAndValidateJSONPayloadMutex.Unlock()
	fake.DecodeAndValidateJSONPayloadStub = nil
	if fake.decodeAndValidateJSONPayloadReturnsOnCall == nil {
		fake.decodeAndValidateJSONPayloadReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.decodeAndValidateJSONPayloadReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *RequestValidator) DecodeAndValidateQueryParams(arg1 *http.Request, arg2 payload.URLDecoder) error {
	fake.decodeAndValidateQueryParamsMutex.Lock()
	ret, specificReturn := fake.decodeAndValidateQueryParamsReturnsOnCall[len(fake.decodeAndValidateQueryParamsArgsForCall)]
	fake.decodeAndValidateQueryParamsArgsForCall = append(fake.decodeAndValidateQueryParamsArgsForCall, struct {
		arg1 *http.Request
		arg2 payload.URLDecoder
	}{arg1, arg2})
	stub := fake.DecodeAndValidateQueryParamsStub
	fakeReturns := fake.decodeAndValidateQueryParamsReturns
	fake.recordInvocation("DecodeAndValidateQueryParams", []interface{}{arg1, arg2})
	fake.decodeAndValidateQueryParamsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *RequestValidator) DecodeAndValidateQueryParamsCallCount() int {
	fake.decodeAndValidateQueryParamsMutex.RLock()
	defer fake.decodeAndValidateQueryParamsMutex.RUnlock()
	return len(fake.decodeAndValidateQueryParamsArgsForCall)
}

func (fake *RequestValidator) DecodeAndValidateQueryParamsCalls(stub func(*http.Request, payload.URLDecoder) error) {
	fake.decodeAndValidateQueryParamsMutex.Lock()
	defer fake.decodeAndValidateQueryParamsMutex.Unlock()
	fake.DecodeAndValidateQueryParamsStub = stub
}

func (fake *RequestValidator) DecodeAndValidateQueryParamsArgsForCall(i int) (*http.Request, payload.URLDecoder) {
	fake.decodeAndValidateQueryParamsMutex.RLock()
	defer fake.decodeAndValidateQueryParamsMutex.RUnlock()
	argsForCall := fake.decodeAndValidateQueryParamsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *RequestValidator) DecodeAndValidateQueryParamsReturns(result1 error) {
	fake.decodeAndValidateQueryParamsMutex.Lock()
	defer fake.decodeAndValidateQueryParamsMutex.Unlock()
	fake.DecodeAndValidateQueryParamsStub = nil
	fake.decodeAndValidateQueryParamsReturns = struct {
		result1 error
	}{result1}
}

func (fake *RequestValidator) DecodeAndValidateQueryParamsReturnsOnCall(i int, result1 error) {
	fake.decodeAndValidateQueryParamsMutex.Lock()
	defer fake.decodeAndValidateQueryParamsMutex.Unlock()
	fake.DecodeAndValidateQueryParamsStub = nil
	if fake.decodeAndValidateQueryParamsReturnsOnCall == nil {
		fake.decodeAndValidateQueryParamsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.decodeAndValidateQueryParamsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *RequestValidator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *RequestValidator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ handler.RequestValidator = new(RequestValidator)
